baseURL = "http://example.org/"
languageCode = "en-us"
theme = "exampleTheme"
title = "Fredriks häftiga titel"

[[menu.main]]
name = "test"
pre = "test"
url = "/a/"
weight = 5
[[menu.main]]
name = "Contact"
pre = "contact"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Tags"
pre = "tag"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Posts"
pre = "pen-tool"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1

[params]
testtext = "min lilla text"

[params.test]
testtext = "testTeXTTTT"
